apiVersion: v1
kind: Pod
metadata:
  name: mysql-client-pod
spec:
  containers:
    - name: mysql-client
      image: mysql:8.0
      command: ["/bin/sh"]
      args: ["-c", "sleep 10000"]
      env:
        - name: MYSQL_HOST
          value: "mysql"        # Ensure this matches your MySQL service name
        - name: MYSQL_USER
          value: "mysqluser"    # MySQL application user
        - name: MYSQL_PASSWORD
          value: "user12345"    # MySQL application user's password
        - name: MYSQL_DATABASE
          value: "sampledb"     # MySQL database name
  restartPolicy: Never
